### PR TITLE
Ml model and calorie estimate

### PR DESCRIPTION
**Pull request by ManasaSRonur**
Modified scripts and csv file to remove unwanted records .
@parvatijay2901 , we might have to change the way files are organized in main branch, especially wrt to input csv files. I see they are in wrong folders.

### CODE REVIEW

**Comment by parvatijay2901** [comment]
@ManasaSRonur can you solve the merge conflict, please? 
image

Mostly it should be me adding the filename param in the physical activity file in main. You can have it how you think it's best to have (either with/without filename param input from front-end):
I forgot to say how I had it to you yesterday,
image
project_integration/recommendation_controller/controller.py  has 
image

You can see your function being called after that..!

**Comment by parvatijay2901** [comment]
I think the last time, I tried solving it and it didnt work out well + made extra commit, so can you please check this?

**Comment by tliu-2** [comment]
**Your branch is still 15 commits behind main.**

**Please rebase with main before making any PRs.** This will allow you - who knows your own code best - to resolve any merge conflicts locally rather than having someone else - who knows your code less - to try to resolve merge conflicts and edit your code.

Your PR also deletes a bunch of files that are used for the tool (such as tool integration scripts). These deletions carry over to main.

See here for more explanation on why you should rebase to the most up to date main commit prior to PR.
https://stackoverflow.com/questions/51404094/should-i-rebase-with-dev-branch-before-making-a-pull-request

**Comment by parvatijay2901** [comment]
Oh also, I felt that lighter shades are better with our background - while displaying the risk score, what do you say? 
I didn't want to experiment much by keeping on changing the colors and trying in the obesity_risk file of yours. Hence, I created the same logic in the frontend with different colors and its fine if you just return the % risk score.

**Comment by ManasaSRonur** [comment]
@parvatijay2901  I have added the filepath argument to physical activity module, as you had done last time
can you share the details of conflict.

**Pull request closed without merging**
